## numpy - make
- array
- reshape
- index
- zeros
- ones
- eye
- like
- empty
- arange
- linspace, logspace
- random : rand, randn (numpy 전용)
- unique : 집합,중복제거, 속성활용시 갯수파악용으로 사용가능
- stack, concat (배열을 합치는 방법)
- split (배열나누기)
- sort

In [2]:
import numpy as np

---

## array
- ndim : 행렬의 차원
- shape : 행렬의 모양


In [2]:
#1차원배열
array = np.array([0,1,2,3])
print(type(array), array)

#2차원배열
array = np.array([
    [0,1],
    [1,2],
    [2,3],
])
print(array)

<class 'numpy.ndarray'> [0 1 2 3]
[[0 1]
 [1 2]
 [2 3]]


In [15]:
#3차원배열
array = np.array([
    [[0,1,2,3],
    [4,5,6,7],
    [8,9,10,11]],
    
    [[0,1,2,3],
    [4,5,6,7],
    [8,9,10,11]]
])
print(array)
print(array.ndim, array.shape)
#차원값 보여줌, 차원별 항목갯수를 보여줌

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
3 (2, 3, 4)


## reshape
- 행렬의 모양을 바꿀 수 있음
-

In [8]:
na = np.array(range(1,9))
na

array([1, 2, 3, 4, 5, 6, 7, 8])

In [256]:
na.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [259]:
rna = np.reshape(na, (4,2))
rna

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [253]:
#추가사항
rnb = np.arange(12).reshape(3,4)
rnb

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
#전치행렬
rna.T, rna.T.shape

(array([[1, 3, 5, 7],
        [2, 4, 6, 8]]), (2, 4))

## index
- 행렬의 특정위치값 가져오기
- 행렬자르기[1:,:3,a:]

In [23]:
print(array)
print(array[1][1][2])
print(array[1,1,2]) #같은기능..

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
6
6


In [261]:
#행렬자르기
i = 2
result = array[0:,1:,i:]
result

array([[[ 6,  7],
        [10, 11]],

       [[ 6,  7],
        [10, 11]]])

In [29]:
#number of dimension(현재 차원 표시)
array.ndim, array[0].ndim, array[0,1].ndim

(3, 2, 1)

In [30]:
#데이터 수정
data = np.array(range(5))
data

array([0, 1, 2, 3, 4])

In [31]:
data[2] = 0
data

array([0, 1, 0, 3, 4])

In [32]:
#슬라이싱으로 특정 범위에 해당하는 모든 요소들의 값 수정 가능
data[3:]=2
data

array([0, 1, 0, 2, 2])

In [34]:
#2차원 행렬 데이터 바꾸기
data = np.array([range(3),range(3,6)])
data

array([[0, 1, 2],
       [3, 4, 5]])

In [41]:
data[1:,1:] = 10
data

array([[ 0,  1,  2],
       [ 3, 10, 10]])

## 영행렬, 일행렬, 단위행렬, 
- zeros
- ones
- eye, identity


In [42]:
#영행렬, 영벡터
z = np.zeros(5)
z

array([ 0.,  0.,  0.,  0.,  0.])

In [43]:
z = np.zeros(5, dtype=int)
z

array([0, 0, 0, 0, 0])

In [44]:
z = np.zeros((2,3,4), dtype = int)
z

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [45]:
#일행렬 일벡터
one = np.ones((2,3,4), dtype=int)
one

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [48]:
#단위행렬
np.identity(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [49]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

## like
- 행렬데이터를 모두 0이나 1로 바꿀 수 있음
- ... 음 이게 왜 궂이 필요하냐면 행렬의 구조를 모를수도 있기때문에 같은 행렬의 구조에 영행렬이나 일행렬을 만들어준다고 생각하면 편하다.

In [60]:
print(data)
np.ones_like(data)

[[ 0  1  2]
 [ 3 10 10]]


array([[1, 1, 1],
       [1, 1, 1]])

In [61]:
np.zeros_like(data)

array([[0, 0, 0],
       [0, 0, 0]])

## empty
- 빈행렬데이터
- 안에 어떤 데이터가 들어갈지 알수없음.

In [262]:
#말그대로 행렬의 구조만 형성하며 안의 내용물을 크게 신경쓰지 않는다. 단지 내부 내용물에 무언가를 기재하지 않을 뿐이다. 그래서 기존에 메모리에 쓰여있는 흔적이 그대로 남아있는 형태가 된다.
np.empty((6,6))

array([[  2.67901935e-258,   3.38690424e-301,   2.49328460e-306,
          1.45750815e-296,   8.88275722e-220,   1.45361876e-296],
       [  2.51519906e-292,   2.65163193e+291,   3.48232260e-308,
          3.39839301e-306,   4.56612585e-191,   2.50127148e-306],
       [  3.49102684e-308,   4.60568421e-287,   1.69212152e-301,
          2.15381464e-282,   5.79296597e-085,   4.08945097e-268],
       [  3.93748462e-268,   3.93748420e-268,   3.12134919e-282,
          2.50161371e-306,   1.63446183e-301,   3.47906307e-308],
       [  4.27214454e-306,   3.47906307e-308,   1.63321223e-301,
          1.39368485e-309,   5.34399107e-306,   3.02552632e-282],
       [  2.36733809e-157,   8.85265423e-220,   2.21673429e-301,
          2.60231353e-258,   7.76709751e+069,   4.59995726e-287]])

## arange
- range와 사용법은 같음
- 큰데이터를 만들때 range 보다 속도가 빠릅니다.

In [263]:
size = int(1E6)
size

1000000

In [63]:
%timeit for x in range(size): x**2
%timeit for x in np.arange(size): x**2

610 ms ± 31 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
368 ms ± 28.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [64]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [66]:
np.arange(2,10,3)

array([2, 5, 8])

## linspace, logspace ★★★★★★★
- 첫값과 끝값을 주고 총 나눠야하는 갯수를 설정하여 균등하게 숫자배치

In [264]:
# 이게 어떤용도로 사용될까? 첫값과 끝값을 먼저 주어주고 총 나눠지는 갯수를 설정한다. linspace는 일반적인 숫자에서 딱딱 나눠놓는다.
np.linspace(0,100,3)

array([   0.,   50.,  100.])

In [265]:
np.linspace(0,100,9)

array([   0. ,   12.5,   25. ,   37.5,   50. ,   62.5,   75. ,   87.5,
        100. ])

In [266]:
# log10(x)=2, log10(x2)=3, log10(x3)=4
# x1:100, x2:1000, x3:10000
np.logspace(2,4,3)

array([   100.,   1000.,  10000.])

In [268]:
np.logspace(2,4,5)

array([   100.        ,    316.22776602,   1000.        ,   3162.27766017,
        10000.        ])

In [76]:
np.logspace(2,3,10)

array([  100.        ,   129.1549665 ,   166.81005372,   215.443469  ,
         278.25594022,   359.38136638,   464.15888336,   599.48425032,
         774.26368268,  1000.        ])

## random
- seed : 랜덤값을 결정해주는 특정 값.(정해져있는 숫자모듬이랄까?)
- rand : uniform(균등분포)하게 랜덤값 뽑아줌. (뽑히는 숫자의 횟수가 균등분포)
- randn : gaussian(정규분포)하게 랜덤값 뽑아줌 (뽑하는 숫자의 횟수가 정규분포)
- randint : 정수를 랜덤하게 뽑아줌 (특정숫자보다 작고 0을 포함하는 양수의 정수값)
- shuffle : 섞어주는함수
- choice : 어러개에서 선택해주는 함수 입니다

In [320]:
np.random.seed(1)
rd = np.random.rand(10)
rd

array([  4.17022005e-01,   7.20324493e-01,   1.14374817e-04,
         3.02332573e-01,   1.46755891e-01,   9.23385948e-02,
         1.86260211e-01,   3.45560727e-01,   3.96767474e-01,
         5.38816734e-01])

In [285]:
#rand 균등분포하게 뽑는다. 그냥 0~1사잇값을 균등한 확률로 뽑음을 의미함
rd = np.random.rand(2,5)*100
rd

array([[ 74.53215102,  26.45493143,  99.97691169,  57.37319011,
         63.90589712],
       [ 48.9699603 ,  88.93747539,  87.4510267 ,  84.77899824,
         64.77238597]])

In [4]:
#randn 정규분포하게 뽑는다는것은 대략 z값으로서의 확률적 뽑힘가능성을 보여주는 것일것이다. 그래서 대체로 -2~2사이값이 주로 나오고 범위를 초과하는 숫자는 드물게 나올것이다. 앞자리가 3이라면 아주 대박임
rdn = np.random.randn(2,5)
rdn

array([[ 2.52227862, -1.49240904, -0.58108843, -1.35610389, -0.64275288],
       [-0.45385963, -0.80388546,  0.78923246,  1.46104637, -0.20051015]])

In [311]:
np.random.randint(10) # 10보다 작은 양의 정수

3

In [341]:
np.random.randint(3,9) # 3부터 9사이의 정수 

4

In [160]:
np.random.randint(5,11,(3,3)) # 5를 포함하며 크고 11보다는 작은 수, 사이즈

array([[10,  7,  9],
       [ 8, 10,  8],
       [10,  5,  8]])

In [162]:
np.random.randint(5, size=(3,3)) #

array([[4, 3, 4],
       [4, 4, 1],
       [0, 4, 2]])

In [411]:
# data = np.array([range(4),range(4,8)])
data = np.arange(1,16).reshape(5,3)
print(data)

np.random.shuffle(data[1:4])

print(data.shape)
data

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
(5, 3)


array([[ 1,  2,  3],
       [ 7,  8,  9],
       [10, 11, 12],
       [ 4,  5,  6],
       [13, 14, 15]])

In [590]:
#choice 특정값, 횟수, replace, p=뽑기확률분포
np.random.choice(5, 20, replace=True, p=[0.1, 0.1, 0.25, 0.50, 0.05])

array([2, 4, 3, 3, 3, 0, 1, 2, 3, 2, 2, 3, 2, 3, 0, 3, 0, 0, 2, 3], dtype=int64)

In [ ]:
np.random.choice(45, 6)

## unique
- 집합개념이며 중복을 제거한 내용물을 index형태로 반환한다.
- 응용하면 인덱스와 인덱스 갯수를 반환하게 할 수 있다. 두개의 리스트를 반환하므로 받아주는 변수도 두개여야한다.

In [488]:
data = np.array([range(4),range(1,5),range(2,6)])
data

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5]])

In [414]:
#unique 속성을 활용하면 인덱스와 그 인덱스의 카운트를 각각 리스트로 반환한다. 행렬의 요소별 갯수를 셀때 유용하게 사용할 수 있다.
index, count = np.unique(data, return_counts=True)
print(index)
print(count)

[0 1 2 3 4 5]
[1 2 3 3 2 1]


## stack
- 행렬을 쌓는것처럼 합치는 방법


In [427]:
na1 = np.arange(6)
na2 = np.arange(6,12)
print(na1, na1.shape)
print(na2, na2.shape)

[0 1 2 3 4 5] (6,)
[ 6  7  8  9 10 11] (6,)


In [428]:
na3 = np.stack((na1,na2))
print(na3,na3.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] (2, 6)


In [440]:
#axis 가 0이 아니면 세로로 쌓는다.
na4 = np.stack((na1,na2),axis=1)
print(na4, na4.shape)
na5 = np.stack((na2,na1))
print(na5)

[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]] (6, 2)
[[ 6  7  8  9 10 11]
 [ 0  1  2  3  4  5]]


In [193]:
na1 = np.random.randint(10,size=(2,3))
na2 = np.random.randint(10,size=(2,3))
print(na1, na1.shape)
print(na2, na2.shape)

[[4 0 0]
 [3 4 9]] (2, 3)
[[3 9 1]
 [2 5 4]] (2, 3)


In [194]:
na3 = np.stack((na1,na2))
print(na3, na3.shape)

[[[4 0 0]
  [3 4 9]]

 [[3 9 1]
  [2 5 4]]] (2, 2, 3)


In [195]:
#axis 가 0이 아니면 세로로 쌓는다.
na4 = np.stack((na1,na2),axis=1)
print(na4, na4.shape)

[[[4 0 0]
  [3 9 1]]

 [[3 4 9]
  [2 5 4]]] (2, 2, 3)


In [442]:
#vstack
#[[0,1,2],[1,2,3],[2,3,4],[3,4,5],[4,5,6]]

ls = []
for i in range(5):
    ls.append(range(i,i+3))
ls

[range(0, 3), range(1, 4), range(2, 5), range(3, 6), range(4, 7)]

In [443]:
np.vstack(ls)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [446]:
#hstack
np.hstack(ls)

array([0, 1, 2, 1, 2, 3, 2, 3, 4, 3, 4, 5, 4, 5, 6])

In [447]:
ls = [list(range(i,i+3)) for i in range(5)]
ls

[[0, 1, 2], [1, 2, 3], [2, 3, 4], [3, 4, 5], [4, 5, 6]]

In [459]:
np.arange(5)[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

## concatenate 결합
- 가로결합 행의 갯수가 같아야한다.
- 세로결함 행의 갯수가 같아야한다.

In [212]:
r1 = np.random.randint(10,size=(2,3))
r1

array([[0, 8, 2],
       [3, 9, 9]])

In [213]:
r2 = np.random.randint(10,size=(3,2))
r2

array([[4, 4],
       [8, 2],
       [1, 6]])

In [214]:
r3 = np.random.randint(10,size=(3,3))
r3

array([[3, 8, 9],
       [7, 0, 5],
       [2, 2, 8]])

In [216]:
np.concatenate((r1,r3))

array([[0, 8, 2],
       [3, 9, 9],
       [3, 8, 9],
       [7, 0, 5],
       [2, 2, 8]])

In [219]:
np.concatenate((r2,r3),axis=1)

array([[4, 4, 3, 8, 9],
       [8, 2, 7, 0, 5],
       [1, 6, 2, 2, 8]])

## split

In [223]:
r = np.arange(10,20)
r

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [224]:
r1 = np.split(r, [5])
r1

[array([10, 11, 12, 13, 14]), array([15, 16, 17, 18, 19])]

In [227]:
r2 = np.split(r,[2,4,6,8])
r2

[array([10, 11]),
 array([12, 13]),
 array([14, 15]),
 array([16, 17]),
 array([18, 19])]

In [228]:
#vsplit - 행렬을 수평단위로 나눠줍니다

In [230]:
r = np.random.randint(10, size=(4,6))
r

array([[5, 0, 5, 9, 8, 6],
       [6, 0, 4, 7, 3, 0],
       [1, 6, 0, 6, 1, 6],
       [4, 2, 5, 4, 6, 2]])

In [238]:
r1, r2, r3= np.vsplit(r,[2,3])
print(r1)
print(r2)
print(r3)

[[5 0 5 9 8 6]
 [6 0 4 7 3 0]]
[[1 6 0 6 1 6]]
[[4 2 5 4 6 2]]


In [251]:
# hsplit - 행렬을 수직단위로 나눠줍니다
r1, r2 ,r3 = np.hsplit(r,[2,5])
print(r1)
print(r2)
print(r3)

[[5 0]
 [6 0]
 [1 6]
 [4 2]]
[[5 9 8]
 [4 7 3]
 [0 6 1]
 [5 4 6]]
[[6]
 [0]
 [6]
 [2]]


## Sort

In [596]:
r1 = np.random.randint(10,size=(3,3))
r1

array([[0, 4, 7],
       [3, 7, 6],
       [5, 0, 2]])

In [597]:
r1.sort()
r1

array([[0, 4, 7],
       [3, 6, 7],
       [0, 2, 5]])

In [599]:
r1.sort(axis = 0)
r1

array([[0, 2, 5],
       [0, 4, 7],
       [3, 6, 7]])

In [485]:
#가장 표면에 가까운 차원에서의 요소를 기준으로 배치하므로 기존에 알던 행렬이 붙는 방식을 생각해서는 안된다.
np.c_[np.arange(1,10).reshape(3,3),np.arange(25,34).reshape(3,3)]

array([[ 1,  2,  3, 25, 26, 27],
       [ 4,  5,  6, 28, 29, 30],
       [ 7,  8,  9, 31, 32, 33]])

In [486]:
np.r_[np.arange(1,10).reshape(3,3), np.arange(25,34).reshape(3,3)]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33]])

In [249]:
np.c_[np.array([1,2,3]),np.array([4,5,6])]
#이렇게 병합할수 있긴하다. 그러나 stack과 concat이 더 빠르다는것 참고

array([[1, 4],
       [2, 5],
       [3, 6]])

In [248]:
np.r_[np.array([1,2,3]),np.array([4,5,6])]

array([1, 2, 3, 4, 5, 6])