## Numpy - Calculate

- 기본연산
- 브로드캐스팅
- 함수
- 퍼포먼스

### 기본연산

In [1]:
#리스트에서의 곱셈
ls = [1,2,3]
ls*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [2]:
[d+3 for d in ls]

[4, 5, 6]

In [4]:
#넘파이 어레이에서의 곱셈
na=np.array([1,2,3])
na

array([1, 2, 3])

In [5]:
na*3

array([3, 6, 9])

In [ ]:
#array간의 곱셈

In [6]:
na1 = np.array([1,2,3])
na2 = np.array([4,5,6])
na1*na2

array([ 4, 10, 18])

In [9]:
#비교연산
na1 == 2, na2 > 5

(array([False,  True, False], dtype=bool),
 array([False, False,  True], dtype=bool))

In [17]:
#비교연삼을 활용한 필터링
na1 = np.array(range(10))
print(na1)
is3 = na1 % 3 == 0
is3

[0 1 2 3 4 5 6 7 8 9]


array([ True, False, False,  True, False, False,  True, False, False,  True], dtype=bool)

In [16]:
na1[is3]

array([0, 3, 6, 9])

In [18]:
na1[na1 % 2 == 0]

array([0, 2, 4, 6, 8])

## 브로드캐스팅
- 일단 연산되려는 shape가 비슷해야한다.
- 행렬의 모든 요소에 같은 연산을 수행
- 행렬내부의 column이나 row에 같은 연산 반복수행

In [23]:
na1 = np.arange(12)
na2 = na1.reshape(3,4)
na3 = np.ones((3,4),dtype=int)
print(na1)
print(na2)
print(na3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [25]:
na2 + na3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [30]:
na2 + 1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
#row에 대한 브로드캐스팅
na4 = np.arange(4)
print(na4)

[0 1 2 3]


In [34]:
na2 + na4

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])

In [48]:
#column에 대한 브로드캐스팅
na5 = np.arange(0,3,1)[:, np.newaxis]
na5

array([[0],
       [1],
       [2]])

In [49]:
na2+na5

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

## functions
- min, max, argmin, argmax
- sum, mean, median, std, var
- all, any
- quartile
- exp, log

In [50]:
r = np.random.randint(10, size=(2,3))
r

array([[3, 7, 8],
       [1, 1, 4]])

In [53]:
#argmin, argmax : index를 출력
r.min(), r.max(), r.argmin(), r.argmax()

(1, 8, 3, 2)

In [54]:
r.mean(), np.sum(r)

(4.0, 24)

In [56]:
np.sum(r, axis=0)

array([ 4,  8, 12])

In [57]:
np.sum(r, axis=1)

array([18,  6])

In [58]:
r

array([[3, 7, 8],
       [1, 1, 4]])

In [59]:
np.median(r)

3.5

In [60]:
np.std(r) #표준편차

2.70801280154532

In [61]:
np.var(r) #분산

7.333333333333333

In [63]:
# all - 모든조건이 충족하면 True
# any - 하나의조건만 충족해도 True
n1 = np.array(range(3,8))
n1

array([3, 4, 5, 6, 7])

In [64]:
n2 = n1
n2

array([3, 4, 5, 6, 7])

In [69]:
n3 = np.array([3,4,0,6,7])
n3

array([3, 4, 0, 6, 7])

In [70]:
np.all(n1 == n2), np.all(n1 == n3)

(True, False)

In [72]:
#any
n4 = np.array(range(10,15))
print(n4)
np.any(n1 == n2), np.any(n1 == n3), np.any(n1 == n4)

[10 11 12 13 14]


(True, True, False)

In [85]:
#사분위수

na = np.arange(101)
na

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [98]:
np.percentile(na, 25)

2.0

In [101]:
na = np.arange(1,6)
na

array([1, 2, 3, 4, 5])

In [99]:
#지수함수
np.exp(na) #값이 너무 작을때 사용하기좋음

array([   2.71828183,    7.3890561 ,   20.08553692,   54.59815003,
        148.4131591 ])

In [100]:
#로그함수
np.log(na) #값이 너무 클때 사용하기 좋음

array([ 0.        ,  0.69314718,  1.09861229,  1.38629436,  1.60943791])

## 성능확인

In [3]:
#10**7개의 리스트에서 3과 5의 배수의 갯수를 찾는데 걸리는 시간

In [4]:
ls=[]
size=int(10E7)

In [7]:
%%time
for d in range(size):
    ls.append(d)
len(ls)

Wall time: 20.3 s


In [5]:
%%time
la = np.arange(size)
len(la)

Wall time: 224 ms


In [8]:
%%time
count = 0
for i in range(len(ls)):
    if (ls[i] %3 == 0) or (ls[i] %5 == 0):
        count += 1
print(count)

46666667
Wall time: 25.7 s


In [6]:
%%time
count = len(la[(la%3==0) | (la%5==0)])
count

Wall time: 2.16 s
