### Quiz

In [1]:
import numpy as np

##### 1. 5개의 1로 이루어진 정수데이터 타입의 벡터를 만드세요

In [4]:
np.ones(5, dtype=int)

array([1, 1, 1, 1, 1])

##### 2. 10개의 1로 이루어진 정수 데이터 타입의 벡터에서 마지막 3개의 데이터는 5가 들어있는 벡터를 만드세요

In [35]:
a=np.ones(7, dtype=int)
b=np.ones(3, dtype=int)*5
np.concatenate((a,b), axis=0)

array([1, 1, 1, 1, 1, 1, 1, 5, 5, 5])

##### 3. 10에서 20까지의 데이터를 가지는 벡터를 만드세요

In [36]:
np.arange(10,21)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

##### 4. 위 벡터의 순서를 바꾸세요

In [37]:
np.arange(10,21)[::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

##### 5. 0부터 8까지의 값을 가지는 3x3 행렬을 만드세요

In [38]:
a = np.arange(9).reshape((3,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

##### 6. 위의 벡터에서  `[[4,5],[7,8]]`  행렬을 만드세요

In [41]:
a[1:,1:]

array([[4, 5],
       [7, 8]])

##### 7. 1에서 10까지의 데이터를 랜덤하게 가지는 3*4 행렬을 만드세요

In [58]:
r = np.random.randint(1,11,size=(3,4))
r

array([[ 6,  9,  2, 10],
       [ 2,  4,  4,  3],
       [ 5, 10,  3,  8]])

##### 8. 위에서 만든 행렬의 unique 한 숫자들 리스트와 각숫자의 갯수를 리스트로 나타내세요

In [62]:
np.unique(r, return_counts=True)

(array([ 2,  3,  4,  5,  6,  8,  9, 10]),
 array([2, 2, 2, 1, 1, 1, 1, 2], dtype=int64))

##### 9. 1에서 12까지에 숫자가 들어간 3*4 행렬을 만드시고 행과 열에 관계없이 데이터를 섞으세요

In [372]:
sh = np.arange(1,13).reshape(3,4)
sh

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [373]:
# np.random.shuffle(sh)
# np.random.shuffle(sh.T)
sh = np.hstack(sh)
np.random.shuffle(sh)
sh.reshape(3,4)

array([[ 1,  3,  5, 11],
       [12,  4,  8,  7],
       [ 2, 10,  6,  9]])

##### 10. 1부터 10까지의 랜덤한 데이터가 들어가는 `3*3`행렬을 만드시고 가장 아래에 위의 데이터를 모두 합한 `1*3`행렬을 추가해서 `4*3`행렬을 만드세요

In [475]:
A = np.random.randint(1,11,size=(3,3))
print(A)
a = np.sum(A, axis = 0)
print([a])



[[ 7 10  8]
 [ 3  3  6]
 [ 5  8  8]]
[array([15, 21, 22])]


In [477]:
X=np.concatenate((A,[a]))
X

array([[ 7, 10,  8],
       [ 3,  3,  6],
       [ 5,  8,  8],
       [15, 21, 22]])

##### 11. 10번문제의 결과로 나온 행렬데이터에서 평균값을 출력하고 평균값보다 큰 숫자들만 유니크한 리스트로 나열하세요 (평균값은 소수 둘째 자리까지만 나타내세요)

In [480]:
xm = X.mean()
print("avg : %.2f"%xm)

avg : 9.67


In [488]:
X[np.array(X > xm)]

array([10, 15, 21, 22])

##### 12. 1부터 20까지의 랜덤숫자를 가지는 5*5 행렬을 만드시고 최대값에는 숫자(MAX), 최소값에는 숫자(MIN)으로 행렬을 바꾸세요

In [530]:
X = np.random.randint(1,21,size=(5,5))
X

array([[ 6, 17,  9, 19, 11],
       [10,  7, 18,  9, 12],
       [15, 16,  4,  6,  1],
       [18,  6, 15, 14,  8],
       [ 6, 16,  6, 11,  8]])

In [531]:
print(X.max(),X.argmax())
print(X.min(),X.argmin())

19 3
1 14


In [532]:
maxx = X.max()
minn = X.min()
X = np.array([[(str(y)+"(Max)" if maxx == y else str(y)+"(Min)") 
      if y in (maxx,minn) else str(y) for y in x] for x in X])
X

array([['6', '17', '9', '19(Max)', '11'],
       ['10', '7', '18', '9', '12'],
       ['15', '16', '4', '6', '1(Min)'],
       ['18', '6', '15', '14', '8'],
       ['6', '16', '6', '11', '8']],
      dtype='<U7')

##### 13. 100에서 130까지의 랜덤 숫자를 가지는 8*8행렬을 만드시고 3의 배수에는 fiz, 5의 배수에는 buz, 3과 5의 배수는 fbz 문자를 출력하세요

In [559]:
Z = np.random.randint(100,131,size=(8,8))
Z

array([[129, 126, 120, 109, 101, 126, 109, 104],
       [102, 125, 129, 116, 124, 110, 105, 117],
       [119, 124, 104, 110, 124, 103, 129, 126],
       [106, 116, 115, 121, 118, 114, 130, 104],
       [118, 109, 124, 119, 129, 114, 129, 123],
       [125, 128, 101, 130, 113, 109, 129, 118],
       [104, 109, 111, 122, 118, 111, 124, 103],
       [114, 110, 120, 118, 112, 124, 122, 103]])

In [560]:
X = [[("fbz" if (a%5==0 and a%3==0) else ("fiz" if a%5==0 else "buz"))
      if (a%5==0 or a%3==0) else str(a)
      for a in row] for row in Z]
X

[['buz', 'buz', 'fbz', '109', '101', 'buz', '109', '104'],
 ['buz', 'fiz', 'buz', '116', '124', 'fiz', 'fbz', 'buz'],
 ['119', '124', '104', 'fiz', '124', '103', 'buz', 'buz'],
 ['106', '116', 'fiz', '121', '118', 'buz', 'fiz', '104'],
 ['118', '109', '124', '119', 'buz', 'buz', 'buz', 'buz'],
 ['fiz', '128', '101', 'fiz', '113', '109', 'buz', '118'],
 ['104', '109', 'buz', '122', '118', 'buz', '124', '103'],
 ['buz', 'fiz', 'fbz', '118', '112', '124', '122', '103']]

##### 14. 리스트 컴프리헨션을 이용하여 아래와 같은 규칙은 갖는 행렬을 만드세요

In [563]:
def sqr_arr(n):
    ls = []
    print("number : ", n)
    return np.array([[i*j for j in range(1,n+1)]for i in range(1,n+1)])
sqr_arr(5)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [564]:
sqr_arr(7)

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 2,  4,  6,  8, 10, 12, 14],
       [ 3,  6,  9, 12, 15, 18, 21],
       [ 4,  8, 12, 16, 20, 24, 28],
       [ 5, 10, 15, 20, 25, 30, 35],
       [ 6, 12, 18, 24, 30, 36, 42],
       [ 7, 14, 21, 28, 35, 42, 49]])